" Vim with all enhancements

set encoding=utf-8
"set fileencodings=utf-8,chinese,latin-1
set fileencoding=utf-8
set fileencodings=utf-8,gbk,gb18030,gb2312,cp936,ucs-bom,latin1
set termencoding=utf-8
"解决菜单乱码
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
"解决consle输出乱码
language messages zh_CN.utf-8

source $VIMRUNTIME/gvimrc_example.vim
source $VIMRUNTIME/mswin.vim

" Use the internal diff if available.
" Otherwise use the special 'diffexpr' for Windows.
if &diffopt !~# 'internal'
  set diffexpr=MyDiff()
endif
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg1 = substitute(arg1, '!', '\!', 'g')
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg2 = substitute(arg2, '!', '\!', 'g')
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let arg3 = substitute(arg3, '!', '\!', 'g')
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  let cmd = substitute(cmd, '!', '\!', 'g')
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction


" Startup {{{
augroup vimrcEx
    au!
    autocmd FileType text setlocal textwidth=80
augroup END
" }}}

colorscheme desert 


"默认最大化窗打开
au GUIEnter * simalt ~x

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                              Plug                                     "
" .vimrc of Bo Liu
" {{{ 一份帮助文件在 https://github.com/hmybmny/vim.cpp.git
" https://github.com/hmybmny/vimrc
" }}}
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" VIM-PLUG BLOCK
" {{{
call plug#begin('C:\Program Files\Vim\vimfiles\plugged')

filetype plugin indent on


" Colors
Plug 'altercation/vim-colors-solarized'
Plug 'tomasr/molokai'
Plug 'colepeters/spacemacs-theme.vim'
Plug 'sheerun/vim-polyglot'

" Editing
"Plug 'SirVer/ultisnips'
Plug 'sjl/gundo.vim'
Plug 'matze/vim-move'
Plug 'jiangmiao/auto-pairs'
Plug 'kana/vim-operator-user'
Plug 'gcmt/wildfire.vim'
Plug 'lilydjwg/fcitx.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'derekwyatt/vim-protodef', { 'for': ['c', 'cpp', 'objc', 'cc'] }
"Plug 'suan/vim-instant-markdown', { 'for': 'markdown' }

" Navigation
Plug 'majutsushi/tagbar', { 'on': 'TagbarToggle' }
Plug 'milkypostman/vim-togglelist'
Plug 'vim-scripts/taglist.vim'
Plug 'derekwyatt/vim-fswitch', { 'for': ['c', 'cpp', 'cc'] }
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
"Plug 'tpope/vim-fugitive'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'dyng/ctrlsf.vim'
Plug 'fholgado/minibufexpl.vim'
"https://github.com/milkypostman/vim-togglelist.git
"https://github.com/vim-scripts/taglist.vim.git

" View
Plug 'Yggdroot/indentLine'
"Plug 'airblade/vim-gitgutter'
Plug 'Valloric/YouCompleteMe'

" Linting
"Plug 'w0rp/ale'

"cd ~
"mkdir ycm_build
"cd ycm_build/
"cmake -G "Unix Makefiles" -DPATH_TO_LLVM_ROOT=~/Downloads/clang+llvm-3.9.1-x86_64-linux-gnu-ubuntu-16.04 . ~/.vim/plugged/YouCompleteMe/third_party/ycmd/cpp
"cmake --build . --target ycm_core
"Plug 'Valloric/YouCompleteMe'
"function! BuildYCM(info)
"    if a:info.status == 'installed' || a:info.force
"        !./install.py --clang-completer
"    endif
"endfunction
"Plug 'Valloric/YouCompleteMe', { 'do': function('BuildYCM') }



" +beautiful {{{
"美化状态栏
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" airline-setting {{{
"加强版状态栏
let g:airline_theme='molokai'
"let g:airline_theme='gruvbox'
"let g:airline_theme='dark'
"使用powerline打过补丁的字体

"let g:airline_powerline_fonts = 1 #only available 
"If you want to use plain ascii symbols, set this variable: >
"let g:airline_symbols_ascii = 1  
"enable modified detection   
let g:airline_detect_modified=1
"关闭状态显示空白符号计数,这个对我用处不大"
"let g:airline#extensions#whitespace#enabled = 0
"let g:airline#extensions#whitespace#symbol = '!'
"开启tabline
let g:airline#extensions#tabline#enabled = 1

"Separators can be configured independently for the tabline, so here is how you can define "straight" tabs:
"let g:airline#extensions#tabline#left_sep = '>'
"let g:airline#extensions#tabline#left_alt_sep = '|'
" the separator used on the left side >
let g:airline_left_sep='<'
" the separator used on the right side >
let g:airline_right_sep='>'

" here is an example of how you could replace the branch indicator with
" the current working directory (limited to 10 characters),
" followed by the filename.
let g:airline_section_b = '%-0.10{getcwd()}'
let g:airline_section_c = '%t'

"tabline中buffer显示编号
let g:airline#extensions#tabline#buffer_nr_show = 1

  if !exists('g:airline_symbols')
    let g:airline_symbols = {}
  endif

  " unicode symbols
  let g:airline_left_sep = ''
  let g:airline_right_sep = ''
  let g:airline_symbols.crypt = '??'
  let g:airline_symbols.linenr = '?'
  let g:airline_symbols.maxlinenr = ''
  let g:airline_symbols.paste = '∥'
  let g:airline_symbols.spell = '?'
  let g:airline_symbols.notexists = '?'
  let g:airline_symbols.whitespace = 'Ξ'

"* enable/disable tagbar integration >
  let g:airline#extensions#tagbar#enabled = 1

"* change how tags are displayed (:help tagbar-statusline) >
  let g:airline#extensions#tagbar#flags = ''
  let g:airline#extensions#tagbar#flags = 'f'
  let g:airline#extensions#tagbar#flags = 's'
  let g:airline#extensions#tagbar#flags = 'p'

" }}}

"打开界面
Plug 'mhinz/vim-startify'
"theme color
Plug 'flazz/vim-colorschemes'
Plug 'tomasr/molokai'
Plug 'morhetz/gruvbox'
Plug 'nanotech/jellybeans.vim'
" theme-setting {{{
" 配色方案
set background=dark
"colorscheme jellybeans
"colorscheme molokai
"colorscheme desert
"colorscheme gruvbox
" }}}

" 图标
"Plug 'ryanoasis/vim-devicons'

"中文帮助文档
Plug 'yianwillis/vimcdoc'
"}}}


" ----------------------------------------------------------------------------
" nerdtree
" 文件树设置 {{{
" ----------------------------------------------------------------------------
"文件树
inoremap <F2> <esc>:NERDTreeToggle<CR>
nnoremap <F2> :NERDTreeToggle<CR>
" NERDTree快捷键
"map <F2> :NERDTreeMirror<CR>
"map <F2> :NERDTreeToggle<CR>
""将F2设置为开关NERDTree的快捷键
"map  :NERDTreeToggle
let NERDTreeMinimalUI=1
let NERDTreeAutoDeleteBuffer=1

let NERDTreeAutoCenter=1
" 是否显示隐藏文件
let NERDTreeShowHidden=1
" 设置宽度
let NERDTreeWinSize=25
" 在终端启动vim时，共享NERDTree
let g:nerdtree_tabs_open_on_console_startup=1
let g:NERDSpaceDelims=1

" 忽略一下文件的显示
let NERDTreeIgnore=['\.pyc','\~$','\.swp']
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "?",
    \ "Staged"    : "?",
    \ "Untracked" : "?",
    \ "Renamed"   : "?",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "?",
    \ "Dirty"     : "?",
    \ "Clean"     : "??",
    \ 'Ignored'   : '?',
    \ "Unknown"   : "?"
    \ }


" NERDTree.vim
let g:neocomplcache_enable_at_startup = 1 

""修改树的显示图标
let g:NERDTreeDirArrowExpandable = '+'
let g:NERDTreeDirArrowCollapsible = '-'
"窗口位置
let g:NERDTreeWinPos='right'
""窗口尺寸
"let g:NERDTreeSize=35
"let g:NERDTreeFileNode
""窗口是否显示行号
let g:NERDTreeShowLineNumbers=1
""不显示隐藏文件
let g:NERDTreeHidden=0
""打开vim时如果没有文件自动打开NERDTree
autocmd vimenter * if !argc()|NERDTree|endif
""当NERDTree为剩下的唯一窗口时自动关闭
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
""打开vim时自动打开NERDTree
"autocmd vimenter * NERDTree

" NERDTress File highlighting
function! NERDTreeHighlightFile(extension, fg, bg, guifg, guibg)
 exec 'autocmd filetype nerdtree highlight ' . a:extension .' ctermbg='. a:bg .' ctermfg='. a:fg .' guibg='. a:guibg .' guifg='. a:guifg
 exec 'autocmd filetype nerdtree syn match ' . a:extension .' #^\s\+.*'. a:extension .'$#'
endfunction

call NERDTreeHighlightFile('jade', 'green', 'none', 'green', '#151515')
call NERDTreeHighlightFile('ini', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('md', 'blue', 'none', '#3366FF', '#151515')
call NERDTreeHighlightFile('yml', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('config', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('conf', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('json', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('html', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('styl', 'cyan', 'none', 'cyan', '#151515')
call NERDTreeHighlightFile('css', 'cyan', 'none', 'cyan', '#151515')
call NERDTreeHighlightFile('coffee', 'Red', 'none', 'red', '#151515')
call NERDTreeHighlightFile('js', 'Red', 'none', '#ffa500', '#151515')
call NERDTreeHighlightFile('php', 'Magenta', 'none', '#ff00ff', '#151515')


" }}}


"文件搜索
Plug 'Yggdroot/LeaderF', { 'do': '.\install.bat' }

"普通模式下，sp前往上一个错误或警告，sn前往下一个错误或警告
nmap sp <Plug>(ale_previous_wrap)
nmap sn <Plug>(ale_next_wrap)
"<Leader>s触发/关闭语法检查
nmap <Leader>s :ALEToggle<CR>
"<Leader>d查看错误或警告的详细信息
nmap <Leader>d :ALEDetail<CR>
"使用clang对c和c++进行语法检查，对python使用flake8进行语法检查
let g:ale_linters = {
\   'c++': ['clang'],
\   'c': ['clang'],
\   'python': ['flake8'],
\}
" }}}

"括号补全
Plug 'jiangmiao/auto-pairs'

""补全
"Plug 'maralla/completor.vim'
"Plug 'maralla/completor-neosnippet'
"Plug 'Shougo/neosnippet-snippets'
"" 补全设置 {{{
""使用tab补全
"inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
"inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
"inoremap <expr> <cr> pumvisible() ? "\<C-y>\<cr>" : "\<cr>"

" }}}

" +lang {{{

" python
"Plug 'python-mode/python-mode', { 'for': 'python' }
"let g:pymode_python = 'python3'

" html
"Plug 'othree/html5.vim',       { 'for': 'html' }
"Plug 'hail2u/vim-css3-syntax', { 'for': 'css' }
"Plug 'mattn/emmet-vim',        { 'for': [ 'html', 'vue', 'css' ] }

" c-c++
Plug 'rhysd/vim-clang-format',           { 'for': [ 'c', 'cpp', 'cc' ] }
Plug 'octol/vim-cpp-enhanced-highlight', { 'for': [ 'c', 'cpp', 'cc' ] }

" javaScript
"Plug 'pangloss/vim-javascript',  { 'for': ['javascript'] }
"Plug 'neoclide/vim-jsx-improve', { 'for': ['javascript', 'javascript.jsx'] }


call plug#end()

"----------------------------------------------------------------------------
"    plug.vim end
"----------------------------------------------------------------------------

" BASIC SETTINGS
" {{{
 
let mapleader = ';'


" Hide buffers
set hidden
set visualbell


function! ToggleFullscreen()
    call system("wmctrl -ir " . v:windowid . " -b toggle,fullscreen")
endf

map <silent> <F11> :call ToggleFullscreen()<CR>
imap <silent> <F11> <esc>:call ToggleFullscreen()<CR>
" autocmd VimEnter * call ToggleFullscreen()

" ----------------------------------------------------------------------------
" Basic mappings
" ----------------------------------------------------------------------------
  

" Edit myvimrc
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" Edit
nnoremap <leader>" viw<esc>a"<esc>hbi"<esc>lel

" Save
inoremap <C-s>     <C-O>:w<cr>
nnoremap <C-s>     :w<cr>
nnoremap <leader>w :w<cr>

" Copy
vnoremap <Leader>y "+y
nmap <Leader>p "+p

" Quit
nnoremap <Leader>q :q<cr>
nnoremap <Leader>Q :qa!<cr>

" Movement in insert mode
inoremap <C-h> <C-o>h
inoremap <C-j> <C-o>j
inoremap <C-k> <C-o>k
inoremap <C-l> <C-o>a
inoremap <C-^> <C-o><C-^>

" ----------------------------------------------------------------------------
" Quickfix
" ----------------------------------------------------------------------------

nnoremap ]q :cnext<cr>zz
nnoremap [q :cprev<cr>zz

" ----------------------------------------------------------------------------
" <tab> / <s-tab> | Circular windows navigation
" ----------------------------------------------------------------------------

nnoremap <tab>   <c-w>w
nnoremap <S-tab> <c-w>W
nnoremap <Leader>hw <C-W>h
nnoremap <Leader>jw <C-W>j
nnoremap <Leader>kw <C-W>k
nnoremap <Leader>lw <C-W>l

" ----------------------------------------------------------------------------
" :CopyRTF
" ----------------------------------------------------------------------------

function! s:colors(...)
return filter(map(filter(split(globpath(&rtp, 'colors/*.vim'), "\n"),
    \                  'v:val !~ "^/usr/"'),
    \           'fnamemodify(v:val, ":t:r")'),
    \       '!a:0 || stridx(v:val, a:1) >= 0')
endfunction

" ----------------------------------------------------------------------------
" <F8> | Color scheme selector
" ----------------------------------------------------------------------------
"  
"set background=dark
"
"let g:molokai_original = 1
""colorschem molokai
"
"function! s:rotate_colors()
"  if !exists('s:colors')
"    let s:colors = s:colors()
"  endif
"  let name = remove(s:colors, 0)
"  call add(s:colors, name)
"  set background=dark
"  execute 'colorscheme' name
"  redraw
"  echo name
"endfunction
"
"nnoremap <silent> <F8> :call <SID>rotate_colors()<cr>
"inoremap <silent> <F8> <esc>:call <SID>rotate_colors()<cr>
"
" }}}

" PLUGINS
" {{{

" ----------------------------------------------------------------------------
" ultisnips
" ----------------------------------------------------------------------------
"
"let g:UltiSnipsSnippetDirectories=["mysnippets"]
"let g:UltiSnipsExpandTrigger="<leader><tab>"
"let g:UltiSnipsJumpForwardTrigger="<leader><tab>"
"let g:UltiSnipsJumpBackwardTrigger="<leader><s-tab>"
"
" ----------------------------------------------------------------------------
" vim-multiple-cursors
" ----------------------------------------------------------------------------

let g:multi_cursor_next_key='<S-n>'
let g:multi_cursor_skip_key='<S-k>'

" ----------------------------------------------------------------------------
" vim-move
" ----------------------------------------------------------------------------

let g:move_key_modifier = 'C'

" ----------------------------------------------------------------------------
" auto-pairs
" ----------------------------------------------------------------------------

" ----------------------------------------------------------------------------
" vim-operator-user
" ----------------------------------------------------------------------------

" ----------------------------------------------------------------------------
" wildfire.vim
" ----------------------------------------------------------------------------

map <SPACE> <Plug>(wildfire-fuel)
vmap <C-SPACE> <Plug>(wildfire-water)

" ----------------------------------------------------------------------------
" indentLine
" ----------------------------------------------------------------------------
  
let g:indentLine_char = '│'

" ----------------------------------------------------------------------------
" tagbar
" ----------------------------------------------------------------------------

inoremap <F8> <esc>:TagbarToggle<cr>
nnoremap <F8> :TagbarToggle<cr>
let g:tagbar_ctags_bin='C:\cygwin64\bin\ctags'
let tagbar_left=1
let tagbar_width=40
let g:tagbar_sort = 0
let g:tagbar_compact=1
"     \ 'l:local:0:1',
"     \ 'p:functions_prototypes:0:1',
let g:tagbar_type_cpp = {
 \ 'ctagstype' : 'c++',
 \ 'kinds'     : [
     \ 'c:classes:0:1',
     \ 'd:macros:0:1',
     \ 'e:enumerators:0:0', 
     \ 'f:functions:0:1',
     \ 'g:enumeration:0:1',
     \ 'm:members:0:1',
     \ 'n:namespaces:0:1',
     \ 's:structs:0:1',
     \ 't:typedefs:0:1',
     \ 'u:unions:0:1',
     \ 'v:global:0:1',
     \ 'x:external:0:1'
 \ ],
 \ 'sro'        : '::',
 \ 'kind2scope' : {
     \ 'g' : 'enum',
     \ 'n' : 'namespace',
     \ 'c' : 'class',
     \ 's' : 'struct',
     \ 'u' : 'union'
 \ },
 \ 'scope2kind' : {
     \ 'enum'      : 'g',
     \ 'namespace' : 'n',
     \ 'class'     : 'c',
     \ 'struct'    : 's',
     \ 'union'     : 'u'
 \ }
\ }

"If you want to open it only if you're opening Vim with a supported file/files use this instead:
autocmd vimenter * :call tagbar#autoopen(1)
"For opening Tagbar also if you open a supported file in an already running Vim:
"autocmd FileType * nested :call tagbar#autoopen(0)
"autocmd FileType c,cpp nested :TagbarOpen

" ----------------------------------------------------------------------------
" vim-fswitch
" ----------------------------------------------------------------------------

nmap <silent> <Leader>fs :FSHere<cr>
let g:fsnonewfiles=1
augroup mycppfiles
   au!
   au BufEnter *.h  let b:fswitchdst  = 'cc,cpp,c'
   au BufEnter *.cc let b:fswitchdst  = 'h'
 augroup END

" ----------------------------------------------------------------------------
" vim-protodef
" ----------------------------------------------------------------------------

let g:protodefprotogetter='~/.vim/plugged/vim-protodef/pullproto.pl'
let g:disable_protodef_sorting=1

" ----------------------------------------------------------------------------
" nerdcommenter
" ----------------------------------------------------------------------------

" ----------------------------------------------------------------------------
" vim-instant-markdown
" ----------------------------------------------------------------------------

autocmd BufNewFile,BufReadPost *.md set filetype=markdown

let g:instant_markdown_slow = 1
let g:instant_markdown_autostart = 0

nnoremap <Leader>md :InstantMarkdownPreview<CR>


" ----------------------------------------------------------------------------
" vim-fugitive
" ----------------------------------------------------------------------------


" ----------------------------------------------------------------------------
" vim-gitgutter
" ----------------------------------------------------------------------------
  
"set updatetime=250
"set signcolumn=yes

" ----------------------------------------------------------------------------
" ale
" ----------------------------------------------------------------------------


" ----------------------------------------------------------------------------
" minibufexpl
" ----------------------------------------------------------------------------

inoremap <F4> <esc>:MBEToggle<cr>
nnoremap <F4> :MBEToggle<cr>

nnoremap ]b :bnext<cr>
nnoremap [b :bprev<cr>

let g:miniBufExplMapWindowNavVim = 1 
let g:miniBufExplMapWindowNavArrows = 1 
let g:miniBufExplMapCTabSwitchBufs = 1 
let g:miniBufExplModSelTarget = 1 
"let g:miniBufExplorerMoreThanOne=1         "自动打开

" ----------------------------------------------------------------------------
" gundo.vim
" ----------------------------------------------------------------------------

nnoremap <Leader>ud :GundoToggle<CR>

set sessionoptions="blank,globals,localoptions,tabpages,sesdir,folds,help,options,resize,winpos,winsize"

if has("win32")

else
  if !strlen(finddir('~/.vim/undofiles'))
      echo "undofiles[~/.vim/undofiles] not found. Now it's being created. Press ENTER or type command to continue."
      !mkdir -p ~/.vim/undofiles
  endif
endif

if v:version >= 703
    set undodir=~/.vim/undofiles
    set undofile
    set colorcolumn=+1 
endif
" ----------------------------------------------------------------------------
" ctrlsf.vim
" ----------------------------------------------------------------------------

nnoremap <c-f> :CtrlSF<CR>

" ----------------------------------------------------------------------------
" ctrlp.vim
" ----------------------------------------------------------------------------

" Disable output, vcs, archive, rails, temp and backup files
set wildignore+=*.o,*.out,*.obj,.git,*.pyc,*.class
set wildignore+=*.zip,*.tar.gz,*.tar.bz2,*.rar,*.tar.xz
set wildignore+=*.swp,*~,._*
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux

let g:ctrlp_map = '<s-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn|vendor/bundle/*\|vendor/cache/*\|public\|spec)$',
  \ 'file': '\v\.(exe|so|dll|swp|log|jpg|png|json)$',
  \ }

" ----------------------------------------------------------------------------
" YouCompleteMe
" ----------------------------------------------------------------------------

set completeopt-=preview

nnoremap <leader>jc :YcmCompleter GoToDeclaration<CR>
nnoremap <leader>jd :YcmCompleter GoToDefinition<CR>
inoremap <leader>; <C-x><C-o>

let g:ycm_complete_in_comments=1
let g:ycm_confirm_extra_conf=0
let g:ycm_collect_identifiers_from_tags_files=0
let g:ycm_min_num_of_chars_for_completion=1
let g:ycm_cache_omnifunc=0
let g:ycm_seed_identifiers_with_syntax=1

" }}}



call plug#end()
" }}}

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" added by teddy 
" 未整理


" Hide buffers
set hidden
set visualbell



"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Copycat: ted
" Version: 3.2.3
" Install: 在linux和windows下无需改动配置文件的内容,对应配置文件夹是vim_3
"          在linux下在 ~/ 目录下,配置文件名改成 .vimrc,路径为 ~/.vimrc
"                        配置文件夹名改成 .vim,路径为 ~/.vim
"          在windows下在 $(vim)/ 目录下,配置文件名改成 _vimrc,路径为 Vim/_vimrc
"                            配置文件夹名改成 vimfiles,路径为 Vim/vimfiles
" NoBugs:  windows下 taglist使用有问题已修复
" Time:    2018.11.6
"
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" 文本格式和排版
"
set formatoptions=tcrqn     " 自动格式化
" Autoindent when starting new line
set autoindent          " 继承前一行的缩进方式，特别适用于多行注释
set smartindent
set lazyredraw
set smartindent         " 为C程序提供自动缩进
set cindent             " 使用C样式的缩进
"set smarttab            " 在行和段开始处使用制表符
set tabstop=2          " 制表符为4
set softtabstop=2      " 统一缩进为4
set shiftwidth=2
set expandtab          " 要用空格代替制表符
"set nowrap             " 不要换行
 
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" 搜索和匹配 
"
set showmatch           " 高亮显示匹配的括号
set matchtime=5         " 匹配括号高亮的时间（单位是十分之一秒）
set scrolloff=10        " 光标移动到buffer的顶部和底部时保持10行距离
set novisualbell        " 不要闪烁

" Enble search highlighting
set hlsearch
set nowrapscan          " 查找到文件头或文件尾时停止
set incsearch          " 边输入边查找
set laststatus=2       " 总是显示状态行
" Ignore case when searching
set ignorecase 
"set ignorecase         " 在搜索的时候忽略大小写
" Don't ignore case when search has capital letter
set smartcase

"" Statusline style
"set statusline=
"set statusline+=%7*\[%n]                                  "buffernr
"set statusline+=%1*\ %<%F\                                "File+path
"set statusline+=%2*\ %y\                                  "FileType
"set statusline+=%3*\ %{''.(&fenc!=''?&fenc:&enc).''}      "Encoding
"set statusline+=%3*\ %{(&bomb?\",BOM\":\"\")}\            "Encoding2
"set statusline+=%4*\ %{&ff}\                              "FileFormat (dos/unix..) 
"set statusline+=%8*\ %=\ row:%l/%L\ (%p%%)\             "Rownumber/total (%)
"set statusline+=%9*\ col:%c\                            "Colnr
"set statusline+=%0*\ \ %m%r%w\ %P\ \                      "Modified? Readonly? Top/bot.
""set statusline=%F%m%r%h%w\[POS=%l,%v][%p%%]\%{strftime(\”%d/%m/%y\ -\ %H:%M\”)} 
                " 我的状态行显示的内容（包括文件类型和解码）
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" 文件设置
"
set shortmess=atI       " 启动的时候不显示那个援助索马里儿童的提示`
set report=0            " 通过使用: commands命令，告诉我们文件的哪一行被改变过
set noerrorbells        " 不让vim发出讨厌的滴滴声
set fillchars=vert:\ ,stl:\     " 在被分割的窗口间显示空白，便于阅读 ,stlnc:\(加了这个wm分割兰有\\\\\\\\\\\\\)
set mouse=a             " 可以在buffer的任何地方使用鼠标（类似office中在工作区双击鼠标定位）
set selection=exclusive
set selectmode=mouse,key
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" 一般设置
"

set viminfo+=!          " 保存全局变量
set history=300         " history文件中需要记录的行数
set nocompatible        " 不要使用vi的键盘模式，而是vim自己的
"显示行号
set nu!
"Show related row numbers
set relativenumber
filetype on             " 侦测文件类型 
set nobackup            " 不要备份文件（根据自己需要取舍） 
"set backup
syntax enable
syntax on           " 语法高亮 

" Highlight line under cursor
set cursorline
set cursorcolumn
set ruler " 打开状态栏标尺
"自动折叠
set fdm=syntax
"留最顶的2层花括号不折叠
set fdl=2
"v:foldstart  折叠首行的行号
"v:foldend  折叠末行的行号
"v:folddashes 一个含有连字符的字符串，用来表示折叠级别
"v:foldlevel  折叠级别
"
set foldtext=MyFoldText()
function MyFoldText()
  let line = getline(v:foldstart)
  "let sub = substitute(line, '/\*\|\*/\|{{{\d\=', '', 'g')
  let sub = substitute(line, '/\\*\\\|\\*/\\\|{{{\\d\\=','','g')
  "return v:foldstart . v:folddashes . v:foldend . v:folddashes . sub
  return v:folddashes . v:foldstart . foldtext()  
endfunction

" vim 文件折叠方式为 marker
"augroup ft_vim
"    au!
"    autocmd FileType vim setlocal foldmethod=marker
"
"    " 打开文件总是定位到上次编辑的位置
"    autocmd BufReadPost *
"      \ if line("'\"") > 1 && line("'\"") <= line("$") |
"      \   exe "normal! g`\"" |
"      \ endif
"augroup END
set magic           " 设置正表达式
set backspace=indent,eol,start  " 这指明在插入模式下在哪里允许 <BS> 删除光标前面的字符。
                " 逗号分隔的三个值分别指：行首的空白字符，换行符和插入模式开始处之前的字符。
set showcmd             " 在 Vim 窗口右下角，标尺的右边显示未完成的命令
" :inoremap ( ()<ESC>i
" :inoremap { {<CR>}<ESC>O
" :inoremap [ []<ESC>i
" :inoremap " ""<ESC>i
" :inoremap ' ''<ESC>i
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" GUI
"
if has("gui_running")           " 如果是图形界面
    " GUI is running or is about to start.
    " Maximize gvim window (for an alternative on Windows, see simalt below).
    set lines=999 columns=999
    set guioptions=m        " 关闭菜单栏
    set guioptions=t        " 关闭工具栏
"   set guioptions=L        " 启动左边的滚动条
"   set guioptions+=r       " 启动右边的滚动条
"   set guioptions+=b       " 启动下边的滚动条
    set clipboard+=unnamed      " 共享剪贴板
    if has("win32")
"       colorscheme torte    " torte配色方案
"       set guifont=Consolas:h11 " 字体和大小
"       autocmd GUIEnter * simalt ~x
    endif
else
  " This is console Vim.
  if exists("+lines")
    set lines=50
  endif
  if exists("+columns")
    set columns=100
  endif
endif
 
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" taglist 
"

"打开TlistToggle
map <F9> :TlistToggle<CR>
"let Tlist_Show_One_File=1               "不同时显示多个文件的tag，只显示当前文件的
"let Tlist_WinWidt = 40                   "设置taglist的宽度
let Tlist_Exit_OnlyWindow=1             "如果taglist窗口是最后一个窗口，则退出vim
"let Tlist_Use_Right_Window=1           "在右侧窗口中显示taglist窗口
let Tlist_Use_Left_Window =1            "在左侧窗口中显示taglist窗口
let Tlist_Auto_Open=1

let Tlist_Compart_Format = 1        " 压缩方式
let Tlist_Exist_OnlyWindow = 1      " 如果只有一个buffer，kill窗口也kill掉buffer
let Tlist_File_Fold_Auto_Close = 0  " 不要关闭其他文件的tags
let Tlist_Enable_Fold_Column = 0    " 不要显示折叠树 (鼠标可以点开)
nmap <silent> <leader>tl :Tlist<cr>
 
"let tags='E:\src\2chromium\1chromium\src\tags'
if has("win32")             
    let Tlist_Ctags_Cmd='C:\cygwin64\bin\ctags' "windows下必须空3个字符,否则解析成gs 
else 
    let Tlist_Ctags_Cmd = '/usr/bin/ctags'
endif
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" netrw
"
let g:netrw_winsize = 35
nmap <silent> <leader>fe :Sexplore!<cr>
 
 
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" winmanager 
"
let g:winManagerWindowLayout='NERDTree|BufExplorer'
"let g:winManagerWindowLayout = 'FileExplorer|TagList'
"let g:winManagerWindowLayout = 'FileExplorer'
let g:winManagerWidth = 35
let g:defaultExplorer = 0
nmap wm :WMToggle<cr>
nmap <C-W><C-F> :FirstExplorerWindow<cr>
nmap <C-W><C-B> :BottomExplorerWindow<cr>
autocmd BufWinEnter \[Buf\ List\] setl nonumber
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" omnicppcomplete
"
set nocp
filetype plugin on
let OmniCpp_DefaultNamespaces = ["std"]     "下面的设置用于当用户预先声明namespace时也能自动补全代码（如使用using std::string） 
"if has("win32")                " 设置代码提示窗口的颜色（默认为粉红色) 
"   highlight Pmenu ctermbg=13 guibg=LightGray 
"   highlight PmenuSel ctermbg=7 guibg=DarkBlue guifg=White 
"   highlight PmenuSbar ctermbg=7 guibg=DarkGray 
"   highlight PmenuThumb guibg=Black
"endif
 
 

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" cscope
"
if has("cscope")
    set csto=0
    set cst
    set nocsverb
    if filereadable("cscope.out")       " add any database in current directory     
        cs add cscope.out
    elseif $CSCOPE_DB != ""         " else add database pointed to by environment       
        cs add $CSCOPE_DB
    endif
    set csverb              " 这个必须放在后面,不然windows上找不到cscope.out
endif
nmap <C-\>s :cs find s <C-R>=expand("<cword>")<CR><CR> :cw<CR>
nmap <C-\>g :cs find g <C-R>=expand("<cword>")<CR><CR> :cw<CR>
nmap <C-\>c :cs find c <C-R>=expand("<cword>")<CR><CR> :cw<CR>
nmap <C-\>t :cs find t <C-R>=expand("<cword>")<CR><CR> :cw<CR>
nmap <C-\>e :cs find e <C-R>=expand("<cword>")<CR><CR> :cw<CR>
nmap <C-\>f :cs find f <C-R>=expand("<cfile>")<CR><CR> :cw<CR>
nmap <C-\>i :cs find i ^<C-R>=expand("<cfile>")<CR>$<CR> :cw<CR>
nmap <C-\>d :cs find d <C-R>=expand("<cword>")<CR><CR> :cw<CR>
"nmap <C-_>s :cs find s <C-R>=expand("<cword>")<CR><CR>
"nmap <C-_>g :cs find g <C-R>=expand("<cword>")<CR><CR>
"nmap <C-_>c :cs find c <C-R>=expand("<cword>")<CR><CR>
"nmap <C-_>t :cs find t <C-R>=expand("<cword>")<CR><CR>
"nmap <C-_>e :cs find e <C-R>=expand("<cword>")<CR><CR>
"nmap <C-_>f :cs find f <C-R>=expand("<cfile>")<CR><CR>
"nmap <C-_>i :cs find i ^<C-R>=expand("<cfile>")<CR>$<CR>
"nmap <C-_>d :cs find d <C-R>=expand("<cword>")<CR><CR>  
" Using 'CTRL-spacebar' then a search type makes the vim window
" split horizontally, with search result displayed in
" the new window.  
nmap <C-Space>s :scs find s <C-R>=expand("<cword>")<CR><CR>
nmap <C-Space>g :scs find g <C-R>=expand("<cword>")<CR><CR>
nmap <C-Space>c :scs find c <C-R>=expand("<cword>")<CR><CR>
nmap <C-Space>t :scs find t <C-R>=expand("<cword>")<CR><CR>
nmap <C-Space>e :scs find e <C-R>=expand("<cword>")<CR><CR>
nmap <C-Space>f :scs find f <C-R>=expand("<cfile>")<CR><CR>
nmap <C-Space>i :scs find i ^<C-R>=expand("<cfile>")<CR>$<CR>
nmap <C-Space>d :scs find d <C-R>=expand("<cword>")<CR><CR>  
 
" Hitting CTRL-space *twice* before the search type does a vertical
" split instead of a horizontal one  
nmap <C-Space><C-Space>s
    \:vert scs find s <C-R>=expand("<cword>")<CR><CR>
nmap <C-Space><C-Space>g
    \:vert scs find g <C-R>=expand("<cword>")<CR><CR>
nmap <C-Space><C-Space>c
    \:vert scs find c <C-R>=expand("<cword>")<CR><CR>
nmap <C-Space><C-Space>t
    \:vert scs find t <C-R>=expand("<cword>")<CR><CR>
nmap <C-Space><C-Space>e
    \:vert scs find e <C-R>=expand("<cword>")<CR><CR>
nmap <C-Space><C-Space>i
    \:vert scs find i ^<C-R>=expand("<cfile>")<CR>$<CR>
nmap <C-Space><C-Space>d
    \:vert scs find d <C-R>=expand("<cword>")<CR><CR>  
